### PR TITLE
observe metrics in recommendation controller

### LINKED ISSUE #672: recommendation metrics lost after restart craned
**Describe the bug**

```
crane_analysis_resource_recommendation
crane_analysis_resource_recommendation
...
```

**Reproduce steps**
1. start craend
2. recommend success once
3. confirm metrics exists
3. restart craned
4. metrics lost

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - K8S Version: 1.22
 - Crane Version: 0.9.0

### PR DESCRIPTION
**Pull request by whitebear009**
#### What type of PR is this?
optimize

#### What this PR does / why we need it:
Currutly recommendation metrics will lost after restart craned because the metrics is created in the progress of calculation of recommend.
If we observe recommendation status in recommedation controller, that can avoid this issue. 

#### Which issue(s) this PR fixes:

Fixes #672

### CODE REVIEW

File: pkg/metrics/analysis.go [hunk 1]
```diff
@@ -13,7 +13,7 @@ var (
 			Name:      "resource_recommendation",
 			Help:      "The containers' CPU/Memory recommended value",
 		},
-		[]string{"apiversion", "owner_kind", "namespace", "owner_name", "container", "resource", "owner_replicas"},
```
Comment (zxh326) [inline pkg/metrics/analysis.go:16]: `owner_replicas`
Why should we discard this label？

Comment (whitebear009) [reply pkg/metrics/analysis.go:16]: Because I thought owner_replicas is not a value that resource recommend needs to care about, there is also no related value in recommendation CRD. 

I refactor thses code with a common method (the input parameter of the observe function was changed from RecommendationContext to Recommendation). If this field needs to be displayed, it needs to be processed separately. 

Please let me know if there is a need to keep this field or any other information I am missing.

Comment (qmhu) [reply pkg/metrics/analysis.go:16]: replicas * resource = total workload resource now
so i think it is useful here.

Comment (whitebear009) [reply pkg/metrics/analysis.go:16]: OK, I will adjust it later

**Comment by whitebear009** [comment]
@qmhu  Already updated, PTAL

**Comment by qmhu** [comment]
> @qmhu Already updated, PTAL

Please fix the lint

**Comment by whitebear009** [comment]
Sorry, miss that. It is fixed now.

**Review by qmhu — APPROVED** [review]
